# default route test
GET localhost:8080/app

# index route test 
GET localhost:8080/app/index.html

# not found test
GET localhost:8080/app/something

# not found test
GET localhost:8080/app/assets/logo.png


# not found test
GET localhost:8080/healthz

# not found test
GET localhost:8080/metrics

# not found test
GET localhost:8080/reset
